plugins {
    id 'com.android.application'
    id 'com.google.gms.google-services'
}

android {
    compileSdk 34

    defaultConfig {
        applicationId "com.elececo.umoney"
        minSdk 23
        targetSdk 33
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    namespace 'com.elececo.umoney'
}

dependencies {
    // FirebaseUI
    implementation 'com.firebaseui:firebase-ui-database:7.2.0'
    implementation 'com.firebaseui:firebase-ui-firestore:8.0.2'
    implementation 'com.firebaseui:firebase-ui-auth:8.0.0'
    implementation 'com.firebaseui:firebase-ui-storage:7.2.0'

    // Firebase (versions managed by BOM)
    implementation platform('com.google.firebase:firebase-bom:33.5.1')
    implementation 'com.google.firebase:firebase-auth'
    implementation 'com.google.firebase:firebase-firestore'

    // Firebase Tasks
    implementation 'com.google.android.gms:play-services-tasks:18.2.0'

    // Other dependencies
    implementation 'com.google.android.gms:play-services-auth:21.2.0'
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.9.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.0'
    implementation 'com.orhanobut:dialogplus:1.11@aar'

    // Fragments
    implementation "androidx.fragment:fragment:1.8.5"
    implementation "androidx.fragment:fragment-ktx:1.8.5"
    implementation 'androidx.lifecycle:lifecycle-viewmodel-android:2.8.7'

    // Testing
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'

    // Glide
    implementation 'com.github.bumptech.glide:glide:4.12.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.12.0'
}
