name: Android CI

on:
  push:
    branches:
      - Dev
  pull_request:
    branches:
      - Dev

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GRADLE_VERSION: 7.4

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Clear Gradle Cache
      run: |
        rm -rf $HOME/.gradle/caches/
        rm -rf $HOME/.gradle/wrapper/

    - name: Build with Gradle
      run: ./gradlew --version

    - name: Run Gradle Build
      run: ./gradlew build
